package wmf.helpers;

import se.web.data.model.Store;

public class WmfStoreProvider {
    public static final Store[] stores = {
            new Store("de114@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Gera"),
            new Store("5045@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Berlin"),
            new Store("DE001@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Fischhalle Geislingen an der Steige"),
            new Store("DE002@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Augsburg"),
            new Store("DE003@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Bonn"),
            new Store("DE004@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Bamberg"),
            new Store("DE005@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Bayreuth"),
            new Store("DE006@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Bielefeld"),
            new Store("DE007@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Metzingen"),
            new Store("DE009@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Wertheim"),
            new Store("DE010@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Darmstadt"),
            new Store("DE011@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Detmold"),
            new Store("DE012@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Dortmund"),
            new Store("DE013@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Düren"),
            new Store("DE014@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Wolfsburg"),
            new Store("DE015@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet DOC Berlin Wustermark"),
            new Store("DE016@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Essen"),
            new Store("DE017@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Köln Schildergasse"),
            new Store("DE018@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Frankfurt am Main Schillerstraße"),
            new Store("DE019@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Freiburg im Breisgau"),
            new Store("DE020@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Fürth"),
            new Store("DE021@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Fulda"),
            new Store("DE022@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Dinslaken"),
            new Store("DE023@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Braunschweig"),
            new Store("DE024@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Bad Fredeburg Schmallenberg"),
            new Store("DE025@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet FOC Selb"),
            new Store("DE026@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Goslar"),
            new Store("DE028@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Pforzheim"),
            new Store("DE029@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Minden"),
            new Store("DE030@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Mönchengladbach"),
            new Store("DE031@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Bochum"),
            new Store("DE032@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Hannover"),
            new Store("DE034@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Herford"),
            new Store("DE035@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Hamburg Mönckebergstraße"),
            new Store("DE036@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Selb"),
            new Store("DE038@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Flensburg"),
            new Store("DE039@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Torgau"),
            new Store("DE040@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Wehr"),
            new Store("DE041@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Kiel Holstenstraße"),
            new Store("DE042@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Mettlach"),
            new Store("DE043@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Köln Hohe Straße"),
            new Store("DE044@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Hamburg Quarree 8"),
            new Store("DE045@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Jettingen-Scheppach"),
            new Store("DE046@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Ingolstadt"),
            new Store("DE047@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Ochtum Park Stuhr"),
            new Store("DE048@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Zweibrücken"),
            new Store("DE049@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Mainz"),
            new Store("DE050@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Ochtrup"),
            new Store("fil6002@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Wien Stock-im-Eisen-Platz"),
            new Store("fil6022@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Gerasdorf bei Wien"),
            new Store("fil5024@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Gießen"),
            new Store("fil5025@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Göttingen"),
            new Store("fil5027@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Hagen"),
            new Store("fil5037@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Hof"),
            new Store("fil5039@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Karlsruhe"),
            new Store("fil5042@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Koblenz"),
            new Store("fil5045@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Berlin"),
            new Store("fil5047@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Berlin"),
            new Store("fil5054@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Münster"),
            new Store("fil5055@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Frankfurt am Main"),
            new Store("fil5076@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Frankenthal"),
            new Store("fil5086@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Hamburg"),
            new Store("fil5092@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Mülheim an der Ruhr"),
            new Store("fil5095@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Remscheid"),
            new Store("fil5101@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Rheine"),
            new Store("fil5103@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Essen - EKZ Limbecker Platz Essen"),
            new Store("fil5104@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Landau in der Pfalz"),
            new Store("fil5106@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Norderstedt"),
            new Store("fil5108@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Lüdenscheid - Stern-Center lüdenscheid"),
            new Store("fil5113@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Görlitz"),
            new Store("fil5128@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Berlin"),
            new Store("fil5131@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Potsdam"),
            new Store("fil5134@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Frankfurt (Oder)"),
            new Store("fil5136@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Leipzig"),
            new Store("fil5146@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Nürnberg"),
            new Store("fil5149@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Berlin"),
            new Store("fil5152@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Schwäbisch Gmünd"),
            new Store("fil5166@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Mainz"),
            new Store("fil5179@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Hanau"),
            new Store("fil5180@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Heilbronn - Stadtgalerie Heilbronn"),
            new Store("fil5182@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Duisburg"),
            new Store("fil5188@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Ludwigshafen am Rhein"),
            new Store("fil5189@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Saarbrücken"),
            new Store("fil5197@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Neuss"),
            new Store("fil5201@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Kaiserslautern"),
            new Store("fil5202@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Hildesheim - Almsstraße"),
            new Store("fil5206@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Aachen"),
            new Store("FILK1XZ@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Berlin"),
            new Store("FILK1YC@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Leipzig"),
            new Store("FILK1YF@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Stuttgart"),
            new Store("fil6004@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Wien"),
            new Store("fil6013@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Wien"),
            new Store("fil6018@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Seiersberg - Shopping City Seiersberg"),
            new Store("fil6021@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Wien"),
            new Store("FIL43RT@wmf.de", "Qwe12345!", "MASTERMATE", "WMF Pop Up Store Seiersberg"),
            new Store("AT001@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Innsbruck"),
            new Store("AT003@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Wien Mariahilfer Straße"),
            new Store("AT006@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Klagenfurt am Wörthersee"),
            new Store("AT007@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Wien Wagramer Straße"),
            new Store("AT008@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Vösendorf"),
            new Store("AT009@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Wien Auhof Center"),
            new Store("AT011@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Pasching"),
            new Store("AT012@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Graz"),
            new Store("AT014@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Linz"),
            new Store("AT017@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Dornbirn"),
            new Store("AT051@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Salzburg Wals DOC Himmelreich"),
            new Store("AT052@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF Outlet Parndorf"),
            new Store("shopbadm@groupeseb.com", "Qwe12345!", "MASTERMATE", "Home & Cook Bad Münstereifel"),
            new Store("shopberlin@groupeseb.com", "Qwe12345!", "MASTERMATE", "Tefal Store Berlin-Alexa"),
            new Store("shopbrehna@groupeseb.com", "Qwe12345!", "MASTERMATE", "Tefal Store Brehna Sandersdorf-Brehna"),
            new Store("shopbremerhaven@groupeseb.com", "Qwe12345!", "MASTERMATE", "Home & Cook Bremerhaven"),
            new Store("DE051@groupeseb.com", "Qwe12345!", "MASTERMATE", "WMF München Weinstraße")
    };
}
